# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES=[
  {
    :hostname => "web",
    :ip => "192.168.100.150",
    :box_name => "centos/7"
  }
]

Vagrant.configure(2) do |config|
    MACHINES.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box_name]
            node.vm.hostname = machine[:hostname]
            node.vm.network "private_network", ip: machine[:ip]
            node.vm.provider "virtualbox" do |v|
              v.memory = 512
            end
            node.vm.provision "ansible" do |ansible|
              ansible.playbook = "playbook.yml"
              ansible.tags = "all"
            end
        end
    end
end

