---
- name: Install redis
  yum:
    name: redis
    state: present

- name: Redis config
  copy:
    src: redis.conf
    dest: "/etc/redis.conf"
    owner: root
    group: root
    mode: 0644
    force: true

- name: Redis restart
  systemd:
    name: redis
    state: restarted

- name: Add apache-user to redis
  user:
   name:   "apache"
   groups: redis

- name: Start & enable redis
  systemd:
    name:    redis
    state:   started
    enabled: true

