- name: common configs
  hosts: all
  become: yes
  roles:
    - common

- name: nfs server
  hosts: server
  become: yes
  roles:
    - nfs-server

- name: nfs client
  hosts: client
  become: yes
  roles:
    - nfs-client
