# -*- mode: ruby -*-
# vim: set ft=ruby :

  Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
  
    config.vm.provision "ansible" do |ansible|
      ansible.verbose = "vvv"
      ansible.playbook = "playbook.yml"
      ansible.inventory_path = "inventory/hosts"
    end
  
    config.vm.define "server" do |server|
      server.vm.hostname = "server"
      server.vm.network "private_network", ip: "192.168.100.15"
    end
  
    config.vm.define "client" do |client|
      client.vm.hostname = "client"
      client.vm.network "private_network", ip: "192.168.100.16"
    end
end
