# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end

  config.vm.define "innodbcluster" do |innodbcluster|
    innodbcluster.vm.network "private_network", ip: "192.168.100.10", virtualbox__intnet: "local"
    innodbcluster.vm.hostname = "innodbcluster"
  end

  config.vm.provision "ansible" do |ansible|
    #ansible.verbose = "vvv"
    ansible.playbook = "playbook.yml"
    ansible.become = "true"
  end

end
