# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

           config.vm.define "server" do |server|
                server.vm.box = "centos/7"
                server.vm.host_name = "server"
                server.vm.network "private_network", ip: '192.168.168.101'
                server.vm.provider :virtualbox do |vb|
                  vb.customize ["modifyvm", :id, "--memory", "256"]
                end
                server.vm.provision "shell", path: "server.sh"
           end

           config.vm.define "backup" do |backup|
                backup.vm.box = "centos/7"
                backup.vm.host_name = "backup"
                backup.vm.network "private_network", ip: '192.168.168.102'
                backup.vm.provider :virtualbox do |vb|
                  vb.customize ["modifyvm", :id, "--memory", "256"]
                end
                backup.vm.provision "shell", path: "backup.sh"
           end
end

