---
- name: mount nfs share
  mount:
    path: /var/www/html/drupal/sites/default/files
    src: 192.168.10.15:/mnt/storage
    fstype: nfs
    opts: noauto,x-systemd.automount,x-systemd.device-timeout=10,timeo=14
    state: mounted

- name: chown -R files directory
  file:
    path: /var/www/html/drupal/sites/default/files
    owner: apache
    group: apache
    mode: 0755
    recurse: yes
