---
   - name: Config for testClient1
     template:
       src: ifcfg-eth1.10-testClient1.j2
       dest: /etc/sysconfig/network-scripts/ifcfg-eth1.10
     notify:
       - restart network
     when: inventory_hostname == "testClient1"

   - name: Config for testClient2
     template:
       src: ifcfg-eth1.20-testClient2.j2
       dest: /etc/sysconfig/network-scripts/ifcfg-eth1.20
     notify:
       - restart network
     when: inventory_hostname == "testClient2"

   - name: Config for testServer1 
     template:
       src: ifcfg-eth1.10-testServer1.j2
       dest: /etc/sysconfig/network-scripts/ifcfg-eth1.10
     notify:
       - restart network
     when: inventory_hostname == "testServer1"

   - name: Config for testServer2
     template:
       src: ifcfg-eth1.20-testServer2.j2
       dest: /etc/sysconfig/network-scripts/ifcfg-eth1.20
     notify:
       - restart network
     when: inventory_hostname == "testServer2"
