---
- name: Common configs
  hosts: all
  become: yes
  roles:
    - common
    - firewalld

- name: Rsyslog & Backup
  hosts: monitoring
  become: yes
  roles:
    - rsyslog-server
    - bacula-server

- name: Make InnoDB Cluster nodes
  hosts:
    - sqlnode01
    - sqlnode02
    - sqlnode03
  become: yes
  roles:
    - rsyslog-sender
    - icluster-node

- name: Install InnoDB Cluster
  hosts: backend01
  become: yes
  roles:
    - icluster-setup

- name: Install MySQL Routers
  hosts:
    - backend01
    - backend02
  become: yes
  roles:
    - icluster-router
    - rsyslog-sender

- name: Install backend01
  hosts: backend01
  become: yes
  roles:
    - bacula-client
    - mysql
    - apache
    - redis
    - drupal
    - php
    - nfsclient

- name: Install backend02
  hosts: backend02
  become: yes
  roles:
    - apache
    - redis
    - drupal
    - php
    - nfsclient

- name: Install haproxies
  hosts:
    - haproxy01
    - haproxy02
  become: yes
  roles:
    - ssl
    - haproxy
    - rsyslog-sender

- name: Install keepalived
  hosts:
    - haproxy01
    - haproxy02
  become: yes
  roles:
    - keepalived

- name: Install NFS server
  hosts:
    - nfsserver
  become: yes
  roles:
    - nfsserver

- name: NFS backup
  hosts:
    - nfsbackup
  become: yes
  roles:
    - nfsbackup
