---
- hosts: all
  become: true
  tasks:
  - name: install packages
    yum: name={{ item }} state=latest
    with_items:
      - bind
      - bind-utils
      - mc
      - policycoreutils-python

  - name: Set timezone
    timezone:
      name: Europe/Moscow

  - name: copy transferkey to all servers and the client
    copy: src=named.zonetransfer.key dest=/etc/named.zonetransfer.key owner=named group=named mode=0644

- hosts: ns01
  become: true
  tasks:
  - name: copy named.conf
    copy: src=master-named.conf dest=/etc/named.conf owner=root group=named mode=0640

  - name: copy zones
    copy: src={{ item }} dest=/etc/named/ owner=root group=named mode=0660
    with_fileglob:
      - named.*

  - name: copy resolv.conf to the servers
    copy: src=servers-resolv.conf dest=/etc/resolv.conf owner=root group=root mode=0644

  - name: set /etc/named permissions
    file: path=/etc/named owner=root group=named mode=0670

  - name: allow to change master zone
    shell: setsebool -P named_write_master_zones 1

  - name: make named permissive for SELinux
    shell: semanage permissive -a named_t

  - name: apply new SELinux context
    shell: restorecon -irv /etc/named/

  - name: ensure named is running and enabled
    service: name=named state=restarted enabled=yes

- hosts: ns02
  become: true
  tasks:
  - name: copy named.conf
    copy: src=slave-named.conf dest=/etc/named.conf owner=root group=named mode=0640

  - name: copy resolv.conf to the servers
    copy: src=servers-resolv.conf dest=/etc/resolv.conf owner=root group=root mode=0644

  - name: set /etc/named permissions
    file: path=/etc/named owner=root group=named mode=0670

  - name: allow to change master zone
    shell: setsebool -P named_write_master_zones 1

  - name: make named permissive for SELinux
    shell: semanage permissive -a named_t

  - name: apply new SELinux context
    shell: restorecon -irv /etc/named/

  - name: ensure named is running and enabled
    service: name=named state=restarted enabled=yes

- hosts: client1
  become: true
  tasks:
  - name: copy resolv.conf to the client1
    copy: src=client-resolv.conf dest=/etc/resolv.conf owner=root group=root mode=0644

  - name: copy rndc conf file
    copy: src=rndc.conf dest=/home/vagrant/rndc.conf owner=vagrant group=vagrant mode=0644

  - name: copy motd to the client1
    copy: src=client-motd dest=/etc/motd owner=root group=root mode=0644

- hosts: client2
  become: true
  tasks:
  - name: copy resolv.conf to the client2
    copy: src=client-resolv.conf dest=/etc/resolv.conf owner=root group=root mode=0644

  - name: copy rndc conf file
    copy: src=rndc.conf dest=/home/vagrant/rndc.conf owner=vagrant group=vagrant mode=0644

  - name: copy motd to the client2
    copy: src=client-motd dest=/etc/motd owner=root group=root mode=0644
