---
- name: Install MySQL repo
  yum:
    name: "https://repo.mysql.com/mysql80-community-release-el7-3.noarch.rpm"
    state: present

- name: Drop MariaDB
  yum:
    name: mariadb-libs
    state: removed

- name: Install mysqlsh
  yum:
    name: mysql-shell
    enablerepo: mysql80-community
    state: present

- name: Copy setupCluster.js
  copy:
    src: setupCluster.js
    dest: /root/setupCluster.js
    owner: root
    group: root
    mode: '0600'

- name: Cluster install
  command: mysqlsh --file setupCluster.js
  args:
    chdir: /root/
    creates: /root/.mysqlsh/mysqlsh.log

