Vagrant.configure("2") do |config|
  config.vm.define "server" do |server|
    server.vm.box = "centos/7"
    server.vm.hostname = "server.test.loc"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "3072"
    end
    server.vm.network "private_network", ip: "192.168.100.101", adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "freeipa-net"
    server.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~root/.ssh
      cp ~vagrant/.ssh/auth* ~root/.ssh
    SHELL
    server.vm.provision :ansible do |ansible|
      ansible.playbook = "server.yml"
    end
  end
  config.vm.define "client" do |client|
    client.vm.box = "centos/7"
    client.vm.hostname = "client.test.loc"
    client.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    client.vm.network "private_network", ip: "192.168.100.102", adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "freeipa-net"
    client.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~root/.ssh
      cp ~vagrant/.ssh/auth* ~root/.ssh
    SHELL
    client.vm.provision :ansible do |ansible|
      ansible.playbook = "client.yml"
    end
  end
end

