# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    config.vm.box_check_update = false
    config.vm.hostname = "mailserver"  
    config.vm.network "private_network", ip: "192.168.10.5"
    config.vm.network "forwarded_port", guest: 25, host: 25, auto_correct: true
    config.vm.define "mailserver"
    config.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "512"
    end
end
