---
- name: mount nfs share
  mount:
    path: /mnt
    src: 192.168.10.15:/mnt/storage
    fstype: nfs
    opts: noauto,x-systemd.automount,x-systemd.device-timeout=10,timeo=14
    state: mounted

- name: Ensure a job that runs at 3.
  cron:
    name: "tar nfs share"
    user: root
    minute: "0"
    hour: "3"
    job: "tar -cvz -f /tmp/archive-$(date +%Y%m%d).tar.gz /mnt/"
